name: Build LLVM15 for Windows test

on:
  workflow_dispatch:
  push:
    branches: [llvm-15.0.2rel]

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: "llvm-15.0.2rel"
          submodules: "recursive"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
         msbuild-architecture: x64
         
      - name: setup vsdevenv
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        shell: cmd
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y

      - name: Build
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF ../llvm
          ninja

      - name: Upload Artifact
        if: failure() || success() 
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Hikari_LLVM15.0.2_Windows
          compression-level: 8
          path: ./build/bin/clang.exe
