name: Download and Repackage Artifacts

on:
  workflow_dispatch:

jobs:
  download_and_repackage:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.6

    - name: Download Artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        name: Hikari_LLVM15.0.2_Windows.zip
        path: build

    - name: Extract Artifacts
      run: |
        Expand-Archive -Path build\Hikari_LLVM15.0.2_Windows.zip -DestinationPath extracted-files

    - name: Copy selected files
      run: |
        mkdir selected-files\bin
        xcopy extracted-files\bin\clang.exe selected-files\bin\ /Y
        xcopy extracted-files\bin\lld-link.exe selected-files\bin\ /Y

    - name: Upload Repackaged Artifacts
      if: failure() || success() 
      uses: actions/upload-artifact@v4.3.3
      with:
        name: repackaged-artifact-15.0.2
        path: selected-files
