name: Download and Repackage Artifacts

on:
  workflow_dispatch:

jobs:
  download_and_repackage:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.6

    - name: Install GitHub CLI
      run: choco install gh

    - name: Download Artifacts from build.yml
      run: |
        gh run download 10506146914 --repo lianquke/Hikari-LLVM15 --name Hikari_LLVM15.0.2_Windows --dir D:\buildx\ --pattern "*.zip"
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: List Files in Directory
      run: |
        Get-ChildItem -Path D:\buildx\ | Format-Table Name, Length
        
    - name: Extract Artifacts
      run: |
        Expand-Archive -Path D:\buildx\Hikari_LLVM15.0.2_Windows.zip -DestinationPath D:\extracted-files

    - name: Copy selected files
      run: |
        mkdirs D:\selected-files\bin
        xcopy D:\extracted-files\bin\clang.exe D:\selected-files\bin\ /Y
        xcopy D:\extracted-files\bin\lld-link.exe D:\selected-files\bin\ /Y

    - name: Upload Repackaged Artifacts
      if: failure() || success() 
      uses: actions/upload-artifact@v4.3.3
      with:
        name: repackaged-artifact-15.0.2
        path: D:\selected-files
